import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Routes, Route, NavLink, Link, useNavigate, useParams, useSearchParams} from 'react-router-dom';
import './style.css';

async function api(path, options={}) {
  const response=await fetch('/api'+path, {...options, headers:options.body instanceof FormData?{}:{'Content-Type':'application/json'}});
  if(!response.ok){const data=await response.json().catch(()=>({detail:'服务暂时不可用'}));throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));}
  return response.status===204?null:response.json();
}
function useData(path){
  const [data,setData]=useState(null),[error,setError]=useState(''),[version,setVersion]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError('');api(path).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));return()=>{active=false};},[path,version]);
  return {data,error,reload:()=>setVersion(v=>v+1)};
}
function Status({error,data}){return error?<p className="error" role="alert">{error}</p>:data===null?<p role="status">正在读取…</p>:null;}
function locationPath(id, locations=[]){let names=[],seen=new Set();while(id&&!seen.has(id)){seen.add(id);let node=locations.find(l=>l.id===id);if(!node)break;names.unshift(node.name);id=node.parent_id;}return names.join(' / ')||'未指定';}
function LocationSelect({locations,value,onChange,optional=false,exclude}){return <select required={!optional} value={value??''} onChange={e=>onChange(e.target.value?Number(e.target.value):null)}><option value="">{optional?'顶层位置':'请选择位置'}</option>{locations.filter(l=>l.id!==exclude).map(l=><option key={l.id} value={l.id}>{locationPath(l.id,locations)}</option>)}</select>}
function Cards({items,locations}){return items.length?<div className="cards">{items.map(i=><Link className="card" to={'/items/'+i.id} key={i.id}>{i.photos?.length?<img src={i.photos.find(p=>p.is_cover)?.url||i.photos[0].url} alt={i.name}/>:<div className="placeholder">物品</div>}<div className="card-body"><h3>{i.name}</h3><p>{locationPath(i.location_id,locations)}</p><small>数量 {i.quantity}</small></div></Link>)}</div>:<div className="empty">这里还没有物品。<Link to="/items/new">登记第一件物品</Link></div>}
function Home(){const items=useData('/items?limit=6'),locations=useData('/locations');return <><header><div><p className="eyebrow">我的家 / 物品管理</p><h1>每件物品，都有归处。</h1><p>记下存放位置，下次需要时轻松找到。</p></div><Link className="button" to="/items/new">＋ 添加物品</Link></header><div className="quick"><Link to="/search"><strong>找一件物品</strong><span>按名称、描述或位置搜索 →</span></Link><Link to="/tree"><strong>看看家里的位置</strong><span>{locations.data?.length??'—'} 个位置 · 查看位置树 →</span></Link></div><h2>最近登记</h2><Status {...items}/>{items.data&&<Cards items={items.data} locations={locations.data||[]}/>}</>}
function ItemList(){const [page,setPage]=useState(0),items=useData('/items?limit=24&offset='+page*24),locations=useData('/locations');return <><header><h1>物品列表</h1><Link className="button" to="/items/new">＋ 添加物品</Link></header><Status {...items}/>{items.data&&<Cards items={items.data} locations={locations.data||[]}/>}<div className="actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page+1} 页</span><button disabled={!items.data||items.data.length<24} onClick={()=>setPage(p=>p+1)}>下一页</button></div></>}
function ItemForm({existing}){const locations=useData('/locations'),categories=useData('/categories'),navigate=useNavigate();const [form,setForm]=useState(existing||{name:'',description:'',quantity:1,location_id:null,category_id:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false);function set(key,value){setForm(f=>({...f,[key]:value}));}async function submit(e){e.preventDefault();setBusy(true);setError('');try{const body={name:form.name,description:form.description,quantity:Number(form.quantity),location_id:form.location_id,category_id:form.category_id,last_confirmed_at:form.last_confirmed_at||null};const result=await api(existing?'/items/'+existing.id:'/items',{method:existing?'PUT':'POST',body:JSON.stringify(body)});navigate('/items/'+result.id);}catch(e){setError(e.message);}finally{setBusy(false);}}return <form className="panel form" onSubmit={submit}><label>物品名称<input required maxLength={200} value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>描述<textarea maxLength={10000} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>存放位置<LocationSelect locations={locations.data||[]} value={form.location_id} onChange={v=>set('location_id',v)}/></label><Link to="/locations">先创建一个位置</Link><label>分类<select value={form.category_id||''} onChange={e=>set('category_id',e.target.value?Number(e.target.value):null)}><option value="">未分类</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>数量<input type="number" required min="1" step="1" value={form.quantity} onChange={e=>set('quantity',e.target.value)}/></label><Status error={error||locations.error} data={true}/><button className="primary" disabled={busy}>{busy?'正在保存…':'保存物品'}</button></form>}
function AddItem(){return <><h1>添加物品</h1><ItemForm/></>}
function EditItem(){const {id}=useParams(),item=useData('/items/'+id);return <><h1>编辑物品</h1><Status {...item}/>{item.data&&<ItemForm existing={item.data}/>}</>}
function Detail(){const {id}=useParams(),item=useData('/items/'+id),locations=useData('/locations'),navigate=useNavigate();const [error,setError]=useState(''),[busy,setBusy]=useState(false);async function upload(e){const file=e.target.files[0];if(!file)return;setBusy(true);setError('');try{const data=new FormData();data.append('file',file);await api('/items/'+id+'/photos',{method:'POST',body:data});item.reload();}catch(e){setError(e.message);}finally{setBusy(false);e.target.value='';}}async function remove(){if(!window.confirm('确认删除物品及其位置历史？照片原文件会保留在存储目录。'))return;try{await api('/items/'+id,{method:'DELETE'});navigate('/items');}catch(e){setError(e.message);}}return <><Status {...item}/>{item.data&&<><header><div><p className="eyebrow">物品详情</p><h1>{item.data.name}</h1></div><Link className="button" to={'/items/'+id+'/edit'}>编辑物品</Link></header><div className="panel"><p className="position">⌖ {locationPath(item.data.location_id,locations.data||[])}</p><p>{item.data.description||'暂无描述'}</p><p>数量：{item.data.quantity}</p><p>最近确认：{item.data.last_confirmed_at?new Date(item.data.last_confirmed_at).toLocaleString():'尚未确认'}</p><div className="actions"><Link className="button" to={'/items/'+id+'/move'}>移动物品</Link><Link to={'/items/'+id+'/history'}>位置历史</Link><button onClick={remove} className="danger">删除物品</button></div></div><h2>物品照片</h2><div className="photos">{item.data.photos.map(p=><a href={p.url} key={p.id} target="_blank" rel="noreferrer"><img src={p.url} alt={item.data.name+(p.is_cover?' · 封面':'')}/></a>)}</div><label className="upload">{busy?'正在上传…':'上传照片（JPG / PNG / WebP，最大 10 MB）'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={upload}/></label><Status error={error} data={true}/></>}</>}
function Move(){const {id}=useParams(),item=useData('/items/'+id),locations=useData('/locations'),navigate=useNavigate();const [to,setTo]=useState(null),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{await api('/items/'+id+'/move',{method:'POST',body:JSON.stringify({to_location_id:to,note})});navigate('/items/'+id+'/history');}catch(e){setError(e.message);}finally{setBusy(false);}}return <><h1>移动物品 · {item.data?.name}</h1><Status {...item}/><form className="panel form" onSubmit={submit}><p>当前：{locationPath(item.data?.location_id,locations.data||[])}</p><label>移动到<LocationSelect locations={locations.data||[]} value={to} onChange={setTo}/></label><label>备注<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><Status error={error||locations.error} data={true}/><button className="primary" disabled={busy||!item.data}>确认移动并记录历史</button></form></>}
function History(){const {id}=useParams(),history=useData('/items/'+id+'/history'),locations=useData('/locations');return <><header><h1>位置历史</h1><Link to={'/items/'+id}>返回物品</Link></header><Status {...history}/><div className="timeline">{history.data?.map(h=><article className="panel" key={h.id}><small>{new Date(h.moved_at).toLocaleString()}</small><h3>{h.from_location_id?locationPath(h.from_location_id,locations.data||[]):'首次登记'} → {locationPath(h.to_location_id,locations.data||[])}</h3><p>{h.note||'无备注'}</p></article>)}</div></>}
function Search(){const [params,setParams]=useSearchParams(),[query,setQuery]=useState(params.get('q')||'');return <><h1>搜索物品</h1><form className="search" onSubmit={e=>{e.preventDefault();if(query.trim())setParams({q:query.trim()});}}><input aria-label="搜索关键词" placeholder="输入物品名称、描述或所在位置" required maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary">搜索</button></form>{params.get('q')&&<Results key={params.get('q')} query={params.get('q')}/>}</>}
function Results({query}){const [page,setPage]=useState(0),results=useData('/search?q='+encodeURIComponent(query)+'&limit=24&offset='+page*24),locations=useData('/locations');return <><Status {...results}/>{results.data&&<><p>“{query}” 的搜索结果</p><Cards items={results.data} locations={locations.data||[]}/><div className="actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page+1} 页</span><button disabled={results.data.length<24} onClick={()=>setPage(p=>p+1)}>下一页</button></div></>}</>}
function Locations(){const locations=useData('/locations'),[editing,setEditing]=useState(null),[form,setForm]=useState({name:'',type:'space',parent_id:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false);function reset(){setEditing(null);setForm({name:'',type:'space',parent_id:null});}async function submit(e){e.preventDefault();setBusy(true);try{await api(editing?'/locations/'+editing:'/locations',{method:editing?'PUT':'POST',body:JSON.stringify(form)});reset();locations.reload();setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}async function remove(id){if(!confirm('确认删除此位置？存在子位置、物品或历史引用时不会删除。'))return;try{await api('/locations/'+id,{method:'DELETE'});locations.reload();}catch(e){setError(e.message);}}return <><header><h1>位置管理</h1><Link to="/tree">查看位置树 →</Link></header><div className="split"><section><Status {...locations}/>{locations.data?.map(l=><article className="location-row" key={l.id}><div><strong>{l.name}</strong><small>{locationPath(l.id,locations.data)}</small></div><button onClick={()=>{setEditing(l.id);setForm({name:l.name,type:l.type,parent_id:l.parent_id});}}>编辑</button><button className="danger" onClick={()=>remove(l.id)}>删除</button></article>)}</section><form className="panel form" onSubmit={submit}><h2>{editing?'编辑位置':'添加位置'}</h2><label>名称<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>类型<input required maxLength={50} placeholder="房间、家具、抽屉…" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}/></label><label>上级位置<LocationSelect optional exclude={editing} locations={locations.data||[]} value={form.parent_id} onChange={parent_id=>setForm({...form,parent_id})}/></label><Status error={error} data={true}/><button className="primary" disabled={busy}>保存位置</button>{editing&&<button type="button" onClick={reset}>取消编辑</button>}</form></div></>}
function TreeNodes({nodes}){return <ul className="tree">{nodes.map(n=><li key={n.id}><details open><summary><strong>{n.name}</strong> <small>{n.type}</small></summary>{n.children.length>0&&<TreeNodes nodes={n.children}/>}</details></li>)}</ul>}
function Tree(){const tree=useData('/locations/tree');return <><header><h1>家里的位置</h1><Link className="button" to="/locations">管理位置</Link></header><Status {...tree}/>{tree.data&&<div className="panel">{tree.data.length?<TreeNodes nodes={tree.data}/>:<p>还没有位置，请先添加。</p>}</div>}</>}
function App(){return <BrowserRouter><aside><Link className="brand" to="/">家中有数<span>家庭物品位置管理</span></Link><nav>{[['/','首页'],['/items','物品列表'],['/items/new','添加物品'],['/search','搜索'],['/locations','位置管理'],['/tree','位置树']].map(([to,label])=><NavLink key={to} to={to} end>{label}</NavLink>)}</nav><p className="aside-note">把物品的位置记下来。</p></aside><main><Routes><Route path="/" element={<Home/>}/><Route path="/items" element={<ItemList/>}/><Route path="/items/new" element={<AddItem/>}/><Route path="/items/:id" element={<Detail/>}/><Route path="/items/:id/edit" element={<EditItem/>}/><Route path="/items/:id/move" element={<Move/>}/><Route path="/items/:id/history" element={<History/>}/><Route path="/search" element={<Search/>}/><Route path="/locations" element={<Locations/>}/><Route path="/tree" element={<Tree/>}/><Route path="*" element={<><h1>页面不存在</h1><Link to="/">返回首页</Link></>}/></Routes></main></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
